"""Spyro the Dragon configuration and offsets."""

from pathlib import Path

from cli.games.registry import (
    GameDefinition,
    StringTableDefinition,
    ThemeDefinition,
    WadDefinition,
    register_game,
)

SPYRO1 = register_game(
    GameDefinition(
        key="ps1.spyro1",
        title="Spyro the Dragon",
        console="ps1",
        region="PAL",
        serial="SCES-01438",
        project_dir=Path("ps1/spyro/1"),
        notes=(
            "Irish replaces the English string slot in SCES_014.38.",
            "Homeworld transition text is patched in the French slot.",
        ),
        rom_markers=(
            b"SCES_014.38",
            b"SPYRO",
        ),
        release_messages=(
            "Convincing dragons to speak Gaeilge...",
            "Politely ignoring Gnasty's spelling notes...",
            "Sharpening fada accents for maximum dramatic effect...",
            "Letting the balloonists argue over pronunciation...",
            "Dusting off a suspiciously old memory card...",
            "Warning sheep that localization is in progress...",
            "Teaching druids not to panic at accented vowels...",
            "Tuning portals to Irish-language frequency...",
            "Asking fairies to stop touching the patch data...",
            "Calming Toasty before the release build...",
            "Trying not to wake Metalhead...",
            "Reminding Spyro that this is still a PAL disc...",
            "Checking if Sparx can proofread...",
            "Bribing a thief to return lost apostrophes...",
            "Translating dragon wisdom into all-caps...",
            "Making sure the portals know where Gaeilge is...",
            "Rescuing vowels from the Gnorc occupation...",
            "Explaining fada marks to the flight levels...",
            "Persuading fairies to stop rearranging bytes...",
            "Double-checking that Spyro can read this upside down...",
            "Searching for one more byte in Beast Makers...",
            "Letting the artisans pretend they helped...",
        ),
        release_message_interval_range=(5.0, 9.0),
        theme=ThemeDefinition(
            header_style="bold gold1",
            accent_style="medium_purple1",
            success_style="spring_green3",
            spinner_style="bright_magenta",
            rule_style="gold3",
        ),
        string_table=StringTableDefinition(
            source_path=Path("ps1/spyro/1/data/strings.py"),
            csv_path=Path("ps1/spyro/1/data/strings.csv"),
            executable_iso_offset=0xC000,
            category_groups={
                "Game state": "UI Strings",
                "Intro / navigation": "UI Strings",
                "HUD / treasure": "UI Strings",
                "Pause menu": "UI Strings",
                "Save/load": "UI Strings",
                "Navigation": "UI Strings",
                "Flight level HUD (0x6c*** region - 8-byte slots)": "UI Strings",
                "Pause/options menu (0x6c*** region)": "UI Strings",
                "Flight level continue prompt": "UI Strings",
                "Homeworld transition screens (French slots repurposed)": "Homeworlds",
                "Homeworld short labels (minimap/inventory)": "Homeworlds",
                "Dragon names section": "Homeworlds",
                "Balloonist": "Balloonist",
                "Balloonist dialogue - first visit": "Balloonist",
                "Balloonist dialogue - second visit": "Balloonist",
                "Balloonist dialogue - prove your worth": "Balloonist",
                "Level names - Gnasty's World": "Level Names",
                "Level names - Peace Keepers": "Level Names",
                "Level names - Beast Makers": "Level Names",
                "Level names - Magic Crafters": "Level Names",
                "Level names - Gnasty's World continued": "Level Names",
                "Level names - Artisans": "Level Names",
            },
            preserve_metadata={
                0x6C17C: 5,
                0x6C1A4: 6,
                0x6C1CC: 7,
                0x6C264: 6,
                0x6C2A4: 4,
                0x6C2EC: 6,
                0x6C30C: 7,
                0x6C38C: 5,
                0x6C3E4: 5,
                0x6C3F4: 7,
                0x6BFA0: 4,
                0x6BFA8: 7,
                0x6BFC0: 5,
                0x6BFF4: 7,
                0x6C01C: 5,
                0x6C05C: 6,
                0x6C064: 5,
                0x6C0CC: 6,
                0x6C0D4: 6,
                0x6C0DC: 6,
                0x6C0E4: 7,
                0x6BFE0: 3,
                0x6BFF0: 2,
                0x6C6A8: 4,
            },
            formula_checks=(
                (0x10B0, 0xEFA8),
                (0x2430, 0x10588),
            ),
        ),
        wad=WadDefinition(
            archive_path=Path("wad.wad"),
            known_subfiles={
                1: "titlescreen sprite sheet (108KB)",
                3: "game ID string",
                20: "unknown small subfile (40KB)",
                32: "timer format strings",
            },
        ),
    )
)
